services:
  web:
    build:
      context: . # Tells docker to look for the Dockerfile in the current directory
      dockerfile: Dockerfile.dev # Tells docker to use the Dockerfile.dev file to build the image
    ports:
      - "3001:3000"
    volumes:
      - /app/node_modules  # Do not try to map the node_modules folder
      - .:/app

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "test"]
    depends_on:
      - web